debmany: Use curl --location to support redirects (Closes: #679225)

diff --git a/debmany/debmany b/debmany/debmany
--- a/debmany/debmany
+++ b/debmany/debmany
@@ -30,7 +30,7 @@ othercmdline="sensible-pager %s"  # viewer for other files
 curdir=`pwd`
 
 # Version of debmany
-version=1.4
+version=1.5
 
 error()
 {
@@ -329,7 +329,7 @@ else
       fi
       # download the package
       debug "Mode3: Start download using curl" # comment
-      curl "$url" >"$file" || error "Failed to download '$url' to '$file'."
+      curl --location "$url" >"$file" || error "Failed to download '$url' to '$file'."
       status=repos-curl
     fi
   fi
